language: bash
sudo: required
services:
- docker
before_install:
- docker pull bitnami/minideb:jessie
before_script:
- sudo apt-get update && sudo apt-get install git
script:
- make
after_success:
- docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
- export REPO=kbase/kb_go
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH
  ; fi`
- docker tag $REPO:$TRAVIS_COMMIT $REPO:$TAG
- if [ "$TAG" == "latest" ] || [ "$TAG" == "develop" ] ; then docker push $REPO:$TAG
  ; fi
env:
  global:
  - secure: DELIRLtxTnZubD0E+OCJli9P74XZT/ygj7cMP1fJnQgenKAZGuR9ljlq5mYvk+iCRBjZb6M4d+qEhSMzBCzNvfhvnbpwL0nBszj4m7tM2jiyFrXbmQ1qlc9lcIWqD/CFRStv1wDXAhy+FU6xGrvho4X8NrZPvzVifCMUPXSWYPu5H2/hK+NLmh2X9NUOmUOM4+SPnnih22UZQLnznr+llSNo19whaThMT3T0XVIHdxtjqDFtTSr0UdArUQ+XRfezeqNfhi14u/QPnLQLLeHmADu6iOKVmoQf4ZJ2zrh1YzkIstnXfVyLuXlercFKgv5vpEFvpZCmTuNERZEjPGyoY39s3/XC/QUH7w4E1CK7w4rNakdL7OPNwUl5OM/9Qms8AFXIcl1NBEQT7LWncFPBKBnK/CKe6e3JTGsnboLB1HdEst3A8+0hO6Rw+hWEDHRDl2A/dcQOMpyDAg0YxasyxNj2MNssVhPnR84WcIDQ7/naC6kcve0cFtpMDAIWskbwKJ7rWLpsDvSw7O7IPdRWQEYao9rR75NI6tPRP1mt2tHhtHwVgzRBiTyV9pvGMI5r0iROuuaT2HY2CFjCSOpeYKp+oM0ONjujp45HrUm5MqOGJPcgI6pKcWl4QtYUA1Fg/LPfiFLbBv5fuSaXW+78Ubd1OTeSRNQyAbfJ4pzDY1Y=
  - secure: dihGflJa9K76b5qedXRu7onlVyp5rrnTC5qADEQlFg2pzTrwv2eVv3KzRPt22cmsKuMJXP0iV0TmHRTApeO0/14tNiC+g5GtFqb6H+OG0CP11b7Lva0ZqhFFGsDVqnbexYjjicTLCsyfEbNuOdY+RBUFWjLzW7UxZe55xQSfd3KnPm5Z7SlT9rFueVJLboCPi+RhSbfBzhJ0NL/uZr6qOCppMykCrjzICvW+RVHGabWCn7yM/oOaATfMsRzGdlO30oEp07b6SHDrfYq8Hy7URtuT8R3z3x0Fp3m6T6lmC3P+tvAp+WNrUVoyUNLTG4MBqcHnzPhpzBFoysLU+oiehN1Z49CSIAQ8JE6wJK4jCUd1R3nXaJhc4T+pXUGEnMowW1ygoGbqlVkAmPi8wt4ix/xyS20nHk4Lzsmj+ydoaB0n5jefhBCmdCEljhGHtIxlZj5pe227/i8yBCnXkdLeyTBsmnitugnJ4xLP3IMvwMj0dy83LdKxEAHIf9mieQQ6lTqLXhEUI11WCrxlf9yS8dCNDFtKLrY/yPY5vwriZfK3aN5u1KErtFfRzxlXefEaG0sQs0aTFtxSKNjsSjUz//1ReeI/icihXcubYlaUXtJFxUnOZfwHGZA1HrcoFWW6f5l46ClMyu+IyBAqxFoFTBHP9ybKJ/dlvQsgVUKvGd8=
  - secure: dwMUpWXCt2hqprOPn/2arzFWUfbdMtcxJ38GCLljfmDxXrb+J0Ch046iqF0GKBBLewNRxUo4nbNNAbYLL3YYEr/kmpNstDK9IsJf6BbXe6Q61M0UwR6zkP3lBc1dD9E2RKBQ/1wxIQbDZf6MSqHbOZ1GHsjTmFzNgR4Myp/I16odUUQWpVXCb/nbXeJDgeUKAXvTBKQFPK4cvGRpmVa5ZjA4+gQuq3Q8bosWLzWgR2SYcfwqaADk7lK+sB/kXwy7RgAJ2ioVs/poe9uYLdVKKdRPPWg4vmHKACTrmucVoFnhznZyYWr6efn3JpDqcMJ38kD/+ML+fZHkFs5shFtelb/AIrRxlgCde08klaGNLOGoyQTbapt7BvzGwxCuCFC8DnbGMS7ISQVzJ9V78S79JkW7UnXAeb8ZOsrCw+BYgv+d6tjaqT3/67WPZvoyAIxpGvRHhwN9dTaFImhPvuumqrzFu66li+7TclD6HDnZ7mlRXMbymzjn5JPwLd24ecfn0CY6vAGp0WKJ6d5wpJ7tr38SBFpdBLzY9OtJ3RBv+rdT2174dmV7SsljNpyuMTHJtjNOZOhOKuN37EMCs/gfsK/ahHk6/5zhvvBo7nONBpyfDeydRRPnYkeYsLSur9zMQNqmVE/g3j5yPFHn7TCADVAm7ogW8Ud2xd4qNdawB4Y=
